---
- hosts: all
  become: yes

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
#    - name: install net-tools
#      apt:
#        install: net-tools

# add "apt install net-tools" to pre-tasks

  roles:
    - geerlingguy.docker
    - initialize