---

- name: Passwordless Sudo For "{{ item }}"
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^%wheel"
    line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  loop:
    - "{{ username }}"

# TODO: Revisit to pin versions to avoid breaking changes.
- name: Install System Updates
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Essential Packages
  apt:
    name: "{{ packages }}"
    state: latest

- name: Suppress Login Message (hushlogin)
  file:
    path: "/home/{{ item }}/.hushlogin"
    mode: 0644
    owner: "{{ item }}"
    group: "{{ item }}"
    modification_time: preserve
    access_time: preserve
    state: touch
  loop:
    - "{{ username }}"

- name: Install docker dependencies and configure repositories
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3
      - python3-pip
      - libffi-dev
      - python3-dev
      - gcc
      - libc6-dev
      - make
    state: present
    update_cache: yes

#- name: Add docker GPG key
#  become: yes
#  apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    state: present
#   keyring: /etc/apt/keyrings/docker.gpg

#- name: Dearmor Docker GPG key
#  ansible.builtin.command: gpg --dearmor /etc/apt/keyrings/docker.gpg

#- name: add docker repository
#  apt_repository:
#    filename: docker 
#    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
#    state: present

#- name: Install docker engine, CLI, and other necessary components
#  become: yes
#  apt:
#    name:
#      - docker-ce
#      - docker-ce-cli
#      - containerd.io
#      - docker-buildx-plugin
#      - docker-scan-plugin
#      - docker-compose-plugin
#    state: present
#    update_cache: yes

- name: Install Python libraries using pip
  become: yes
  pip:
    name:
      - requests
      - docker
      - docker-compose
    state: present
    executable: pip3  # Ensure pip for Python 3 is used

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: 
      - "docker==6.1.3"
      - "docker-compose"

#- name: Install Docker SDK for Python
#  ansible.builtin.pip:
#    name: 
#      - "docker"
#      - "docker-compose"
    