---

- name: Start Docker Compose
  community.docker.docker_compose:
    project_src: /docker
  register: output

#- name: Start Docker
#  shell: docker-compose -f /docker/docker-compose.yml up -d

#- name: Start Docker
#  command: >
#    docker-compose -f /docker/docker-compose.yml up -d
