---

# ==============================
# Amaterasu compose files
# ==============================

- name: Copy amaterasu compose files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/docker/stacks/{{ item }}/compose.amaterasu.yml"
    dest: "/docker/stacks/{{ item }}/compose.amaterasu.yml"
    owner: root
    group: root
    mode: "0644"
  loop:
    - tousou-gate
    - sunrise-mqtt-soup
    - hyperdimension-library
    - osaki-ni-cloud
    - spicy-queen-ctrl
    - neet-game
    - warning-core
  when: inventory_hostname == "amaterasu"

# ==============================
# Holo compose files
# ==============================

- name: Copy holo compose files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/docker/stacks/{{ item }}/compose.holo.yml"
    dest: "/docker/stacks/{{ item }}/compose.holo.yml"
    owner: root
    group: root
    mode: "0644"
  loop:
    - devs-talk
    - warning-core
  when: inventory_hostname == "holo"

# ==============================
# Chibiterasu compose files
# ==============================

- name: Copy chibiterasu compose files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/docker/stacks/{{ item }}/compose.chibiterasu.yml"
    dest: "/docker/stacks/{{ item }}/compose.chibiterasu.yml"
    owner: root
    group: root
    mode: "0644"
  loop:
    - good-day-so-epic
    - warning-core
  when: inventory_hostname == "chibiterasu"
