---
- name: Import "discord music bot" Repository
  git:
    repo: https://github.com/kawadeomkar/discord-music-bot.git
    dest: /home/{{ username }}/repo-kawade/discord-music-bot/
    clone: yes
    update: yes
    version: main
    force: yes
