---

- name: Create Docker Directory
  ansible.builtin.file:
    path: /docker
    state: directory

- name: Create Dashdot Docker Directory
  ansible.builtin.file:
    path: /docker/dashdot
    state: directory

- name: Create Actual Budget Directory
  ansible.builtin.file:
    path: /docker/actual-budget
    state: directory

- name: Create Wiki.js Directory
  ansible.builtin.file:
    path: /docker/wiki-js
    state: directory

- name: Create Photoprism Directory
  ansible.builtin.file:
    path: /docker/photoprism
    state: directory

- name: Create Tandoor Directory
  ansible.builtin.file:
    path: /docker/tandoor
    state: directory

- name: Create Mealie Directory
  ansible.builtin.file:
    path: /docker/mealie
    state: directory

- name: Create Calibre Directory
  ansible.builtin.file:
    path: /docker/calibre
    state: directory

- name: Create Jellyfin Directory
  ansible.builtin.file:
    path: /docker/jellyfin
    state: directory

- name: Create NextCloud Directory
  ansible.builtin.file:
    path: /docker/nextcloud
    state: directory

- name: Create Nginx Directory
  ansible.builtin.file:
    path: /docker/nginx
    state: directory

- name: Create Tailscale Tmp Directory
  ansible.builtin.file:
    path: /tmp/Tailscale
    state: directory

- name: Create Container Directories
  file:
    mode: 0777
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /opt/hass
    - /opt/portainer
    - /opt/prometheus
    - /opt/grafana
    - /opt/homepage
    - /opt/homarr
    - /opt/homarr/icons
    - /opt/uptimekuma
    - /opt/cadvisor
    - /opt/nginx/data
    - /opt/nginx/letsencrypt
    - /opt/filebrowser
    - /opt/pihole/etc-pihole
    - /opt/pihole/etc-dnsmasq.d
    - /opt/actual-data
    - /opt/wikijs
    - /opt/mealie-data
    - /media/drive2/jellyfin/config
    - /media/drive2/data/usenet
    - /opt/nextcloud/appdata
    - /opt/nextcloud/data
    - /opt/nginx/data
    - /opt/nginx/letsencrypt
    - /opt/calibre-data


- name: Create Data Folder
  ansible.builtin.file:
    path: /data
    state: directory

- name: Create Torrent Folder
  ansible.builtin.file:
    path: /data/torrents
    state: directory

- name: Create Usenet Folder
  ansible.builtin.file:
    path: /data/usenet
    state: directory

- name: Create Incomplete Folder
  ansible.builtin.file:
    path: /data/usenet/incomplete
    state: directory

- name: Create Complete Folder
  ansible.builtin.file:
    path: /data/usenet/complete
    state: directory

- name: Create Media Folder
  ansible.builtin.file:
    path: /data/media
    state: directory

- name: Create Torrent Folders
  file:
    mode: 0777
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /data/torrents/books
    - /data/torrents/movies
    - /data/torrents/music
    - /data/torrents/tv

- name: Create Usenet Folders
  file:
    mode: 0777
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /data/usenet/complete/books
    - /data/usenet/complete/movies
    - /data/usenet/complete/music
    - /data/usenet/complete/tv

- name: Create Media Folders
  file:
    mode: 0777
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /data/usenet/complete/books
    - /data/usenet/complete/movies
    - /data/usenet/complete/music
    - /data/usenet/complete/tv

# What does this do?
#- name: Changing Permissions of "/opt" 
#  shell: chown ookami:ookami /opt
